version: "3.7"

services:
  jaegertracing:
    image: jaegertracing/all-in-one:latest
    container_name: jaegertracing
    hostname: jaegertracing
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/foo/swagger.json
    volumes:
      - "/planet/src/doc:/foo"
    ports:
      - "801:8081"
  portainer:
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - portainer_data:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  gateway:
    image: planet_app2:latest
    container_name: gateway
    hostname: gateway
    volumes:
      - "/c/www/planet/env:/env"
    ports:
      - "8080:8080"
    command: ./app gateway
    deploy:
      mode: replicated
      replicas: 1
      labels: [server=gateway]
    networks:
      - local_elastic-jaeger
  bas:
    image: planet_app2:latest
    container_name: bas
    hostname: bas
    volumes:
      - "/c/www/planet/env:/env"
    ports:
      - "50050:50050"
    command: ./app serve Bas
    deploy:
      mode: replicated
      replicas: 1
      labels: [server=bas]
    networks:
      - local_elastic-jaeger
  pro:
    image: planet_app2:latest
    container_name: pro
    hostname: pro
    volumes:
      - "/c/www/planet/env:/env"
    ports:
      - "50051:50051"
    command: ./app serve Pro
    deploy:
      mode: replicated
      replicas: 1
      labels: [server=pro]
    networks:
      - local_elastic-jaeger
  usr:
    image: planet_app2:latest
    container_name: usr
    hostname: usr
    volumes:
      - "/c/www/planet/env:/env"
    ports:
      - "50052:50052"
    command: ./app serve Usr
    deploy:
      mode: replicated
      replicas: 1
      labels: [server=usr]
    networks:
      - local_elastic-jaeger
  ord:
    image: planet_app2:latest
    container_name: ord
    hostname: ord
    volumes:
      - "/c/www/planet/env:/env"
    ports:
      - "50053:50053"
    command: ./app serve Ord
    deploy:
      mode: replicated
      replicas: 1
      labels: [server=ord]
    networks:
      - local_elastic-jaeger
volumes:
  data:
    driver: local
  portainer_data:
  jaeger_data:
networks:
  local_elastic-jaeger:
    driver: overlay