version: "3.7"

services:
  gateway:
    image: planetapp:latest
    container_name: gateway
    hostname: gateway
    volumes:
      - "/c/www/planet/env:/env"
    ports:
      - "8888:8888"
    command: ./app gateway
  bas:
    image: planetapp:latest
    container_name: bas
    hostname: bas
    volumes:
      - "/c/www/planet/env:/env"
    ports:
      - "55550:55550"
    command: ./app serve Bas
networks:
  elastic-jaeger:
    driver: bridge
volumes:
  data:
    driver: local
  portainer_data:
  jaeger_data: